services:
  kopia:
    image: kopia/kopia:latest
    container_name: Kopia
    user: "0:0"
    restart: "unless-stopped"
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --address=0.0.0.0:51515
      - --server-username=admin
      - --server-password=claveSegura123
    volumes:
      - /mnt/kopia:/tmp:shared
      - /home/tuusuario/docker/Kopia-Ubuntu/config:/app/config
      - /home/tuusuario/docker/Kopia-Ubuntu/cache:/app/cache
      - /home/tuusuario/docker/Kopia-Ubuntu/logs:/app/logs
      - /:/data:ro
    environment:
      KOPIA_PASSWORD: claveSegura123
      TZ: America/Argentina/Buenos_Aires
      USER: tuusuario
